/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Book;
import Master.BookDAO;
import Master.EmployeeMain;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Ahmed yehia
 */
public class FindBook extends javax.swing.JFrame {

    /**
     * Creates new form FindBook
     */
   
     BookDAO DB;
     BookTableModel tbl;
     String Employee_Id;

    public FindBook(String id) {
        Employee_Id=id;
          try{
            DB=new BookDAO();
        }
        catch(Exception e){
          JOptionPane.showMessageDialog(this, "Error"+e, "Error", JOptionPane.ERROR_MESSAGE);
        }
        initComponents();    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        ViewButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SearchField = new javax.swing.JTextField();
        BAck = new javax.swing.JButton();
        History = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SearchButton.setBackground(new java.awt.Color(41, 128, 185));
        SearchButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        SearchButton.setForeground(new java.awt.Color(255, 255, 255));
        SearchButton.setText("Search");
        SearchButton.setBorderPainted(false);
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        Table.setBackground(new java.awt.Color(249, 249, 249));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Author", "Id", "Copies"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        ViewButton.setBackground(new java.awt.Color(41, 128, 185));
        ViewButton.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        ViewButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewButton.setText("View");
        ViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewButtonActionPerformed(evt);
            }
        });

        DeleteButton.setBackground(new java.awt.Color(41, 128, 185));
        DeleteButton.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        DeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(44, 62, 80));
        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 100));
        jLabel1.setText("Find Book");

        SearchField.setBackground(new java.awt.Color(236, 240, 241));
        SearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFieldActionPerformed(evt);
            }
        });

        BAck.setBackground(new java.awt.Color(41, 128, 185));
        BAck.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        BAck.setForeground(new java.awt.Color(255, 255, 255));
        BAck.setText("Back");
        BAck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAckActionPerformed(evt);
            }
        });

        History.setBackground(new java.awt.Color(41, 128, 185));
        History.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        History.setForeground(new java.awt.Color(255, 255, 255));
        History.setText("History");
        History.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(SearchButton)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(History)
                .addGap(29, 29, 29)
                .addComponent(ViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(BAck, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BAck, DeleteButton, History, ViewButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BAck, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(History, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        try{
            ArrayList<Book> lst= DB.Search(SearchField.getText());
            tbl=new BookTableModel(lst);
            Table.setModel(tbl);
        } catch (SQLException ex) {
            Logger.getLogger(FindBook.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TableMouseClicked

    private void ViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewButtonActionPerformed
        int row=Table.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(this, "You must select an Book", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            try {
                Book e=DB.Search(""+Table.getValueAt(row,2)).get(0);
                ViewBook v=new ViewBook(FindBook.this,DB,e,true);
                v.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(FindBook.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        refresh();
    }//GEN-LAST:event_ViewButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        int row=Table.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(this, "You must select an Book", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int res= JOptionPane.showConfirmDialog(this, "Delete this Book?", "Confirm",JOptionPane.YES_NO_OPTION ,JOptionPane.QUESTION_MESSAGE);
        if(res!=JOptionPane.YES_OPTION){
            return;
        }
        try {
            Book e=DB.Search(""+Table.getValueAt(row,2)).get(0);
            DB.DeleteBook(e.getId());
        } catch (SQLException ex) {
            Logger.getLogger(FindBook.class.getName()).log(Level.SEVERE, null, ex);
        }

        refresh();
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void SearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFieldActionPerformed

    }//GEN-LAST:event_SearchFieldActionPerformed

    private void BAckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAckActionPerformed
          EmployeeMain r=new EmployeeMain(Employee_Id);
             r.setVisible(true);
             this.setVisible(false);
    }//GEN-LAST:event_BAckActionPerformed

    private void HistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryActionPerformed
        int row=Table.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(this, "You must select an Book", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            try {
                Book e=DB.Search(""+Table.getValueAt(row,2)).get(0);
                System.out.println(e.getId());
                
                BookHistory v=new BookHistory(FindBook.this,e,true);
                v.setVisible(true);
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_HistoryActionPerformed

    /**
     * @param args the command line arguments
     */
   
     void refresh(){
            try{
                ArrayList<Book> lst= DB.Search(SearchField.getText());
               tbl=new BookTableModel(lst);
                Table.setModel(tbl);
            } catch (SQLException ex) {
               Logger.getLogger(FindBook.class.getName()).log(Level.SEVERE, null, ex);
           }
       }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAck;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton History;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchField;
    private javax.swing.JTable Table;
    private javax.swing.JButton ViewButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
